# Generated by Django 5.1.3 on 2024-11-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
