# Generated by Django 5.1.3 on 2024-11-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
